### ISSUE TITLE
Question: Get word by index

### ISSUE THREAD

**Issue by mcroad** [rust-bitcoin/rust-bip39#19]
I have a situation where I need to access a word in some language by some index `[0, 2047]`. It does not seem like it's currently possible to do this. 

Specifically, I am attempting to implement the current SeedQR encoding used by @SeedSigner. The encoding is a list of length *n* of 4-digit numbers each corresponding to an index in the word list.

I can submit a PR addressing this issue, but I would like to hear the maintainers' opinion as to the best way to do it. The simplest solution that comes to mind would be to make [`Language::word_list`](https://github.com/rust-bitcoin/rust-bip39/blob/master/src/language/mod.rs#L85) public instead of just create-visible.

**Comment by Dr-Julius-No** [comment]
I came to post the same thing but for a different project.

Apart from the word lists themselves being private, I can find no reason for the `Language::find_word` to be `pub(crate)` only.

**Comment by Dr-Julius-No** [comment]
Ping @stevenroose , Pull requests in this repository look stale (the word length mod 3 in particular) -- are you amenable to discussing at least the `language` module? I can whip up some PRs if yes.

**Comment by mcroad** [comment]
Fixed in #20.
