### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by pezcore** [rust-bitcoin/rust-bip39#31]
Is this project still maintained and are there any plans for a release? I noticed the last release on crates.io was about a year and a half ago, but it appears there have been several desirable feature upgrades merged into `master` since then.

**Comment by tcharding** [comment]
Yes this repo is maintained still. I've put up a [release PR](https://github.com/rust-bitcoin/rust-bip39/pull/32) @stevenroose is the release boss, he will get to it some time :)

**Comment by pezcore** [comment]
Thanks!
