### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MaxFangX** [rust-bitcoin/rust-bip39#35]
The latest version of this crate `1.0.1` was released on April 1st, 2021 - over 1 year and 8 months ago. Since then, there's been a PR to add `Zeroize` support which we'd like to use without having to specify a git dependency. Would you mind cutting a new release so we can use the zeroize feature via crates.io?

**Comment by tcharding** [comment]
We have a release PR up, just waiting for @stevenroose to get to it.

**Comment by pezcore** [comment]
`2.0.0` release was cut 27 Feb 2023. recco close this issue.
