### ISSUE TITLE
`bip39::Language::find_word` returning indices starting from 0 is a footgun for the user

### ISSUE THREAD

**Issue by plebhash** [rust-bitcoin/rust-bip39#77]
I wanted a tool where I could conveniently create a BIP39 seed phrase from a safe source of entropy. I ended up with [`seed_entropy_blower`](https://github.com/plebemineira/seed_entropy_blower).

I originally wrote this code as part of the UI:
```rust
    println!("\nBIP39 seed phrase ✍️🗝️");
    println!("position|word|number");
    let mut i = 1;
    for word in bip39.word_iter() {
        println!("{}|{}|{}", i, word, bip39::Language::English.find_word(word).expect("this should be a valid word"));
        i+=1;
    }
```

which rendered:
```
BIP39 seed phrase ✍️🗝️
position|word|number
1|card|276
2|bomb|201
3|process|1372
4|antenna|78
5|twin|1883
6|weird|1993
7|fine|694
8|leopard|1026
9|glimpse|793
10|taste|1777
11|appear|84
12|wealth|1985
13|cash|282
14|ice|897
15|pear|1296
16|cargo|277
17|trade|1845
18|minute|1130
19|dish|505
20|unfold|1897
21|cable|255
22|inhale|925
23|poverty|1352
24|level|1029
```

I went to check the official [BIP39 github page](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) and noticed that:
- my UI prints `card` as `276`
- the list has `card` as `277`

So I had to adapt my code to:
```diff
    println!("\nBIP39 seed phrase ✍️🗝️");
    println!("position|word|number");
    let mut i = 1;
    for word in bip39.word_iter() {
-        println!("{}|{}|{}", i, word, bip39::Language::English.find_word(word).expect("this should be a valid word"));
+        println!("{}|{}|{}", i, word, bip39::Language::English.find_word(word).expect("this should be a valid word")+1); 
        i+=1;
    }
```

But that left me worndering: why is [`bip39::Language::find_word`](https://docs.rs/rust-bip39/latest/bip39/enum.Language.html#method.find_word) API returning using the indices starting from 0?

This standard of  indices starting from 1 seems to be the one that's widely used:
- https://tinyseed.io/bip-39/
- https://www.blockplate.com/pages/bip-39-wordlist
- https://privacypros.io/bip39-word-list/

Speaking from my own experience, I feel this API is a massive footgun for the users of this crate. I'm glad I verified and was able to adapt my code to avoid issues, but I'm reporting this here anyways.

**Comment by storopoli** [comment]
Yeah the old debate about `0`-index vs `1`-index.
This would be a breaking change and also annoying AF since the last `i+1` new API word would probably overflow the returning `u16` type.

I would just add a

```rs
/// # Warning
///
/// Lorem ipsum dolor ....
```

in the docstring of `find_word`.

**Comment by tcharding** [comment]
I understand that you had felt some pain because of this off-by-one error but the whole issue and fix is a non-issue IMO, in computer science indecies start at 0. If github or other wallets choose to call the word stored in an array at index 0 "word 1" that is not our problem. Sorry to be harsh, I tried to say it in a more friendly way before :)
